### ISSUE TITLE
how to get result from async listener?

### ISSUE THREAD

**Issue by JunjieBian** [zpxp/channel-event#6]
sample:

const hub = createHub();
const channel = hub.newChannel();

const mock = aysnc (data) => {
   return await Promise.resolve(() => {
    setTimeout((e)=> {
      return 'timeout'
    }, 2000)
  })
}

channel.listen("test", mock);

const result = channel.send('test', {a:123})
console.log(result) //expect 'timeout'

**Comment by zpxp** [comment]
You cant return a value from `setTimeout`, it will just disappear into the JS engine. Also, `channel.listen` is synchronous, so it will return the promise itself, not the promise result. The value of `result` will just be a promise that you can then call `.then` on to wait for the promise to resolve. 

Change your code to this.
```ts
const hub = createHub();
const channel = hub.newChannel(channelId);

const mock =  (data) => {
    return new Promise((resolve) => {
        setTimeout((e)=> {
            resolve('timeout');
        }, 2000)
    })
}

channel.listen("test", mock);

const dictionaryResult = channel.send('test', {a:123})
dictionaryResult[channelId].then(r => {
    console.log(r) //expect 'timeout'
})
```

You can also use a generator in `channel.runGenerator` and use `delay` instead of the timeout.

**Comment by JunjieBian** [comment]
> You cant return a value from `setTimeout`, it will just disappear into the JS engine. Also, `channel.listen` is synchronous, so it will return the promise itself, not the promise result. The value of `result` will just be a promise that you can then call `.then` on to wait for the promise to resolve.
> 
> Change your code to this.
> 
> ```ts
> const hub = createHub();
> const channel = hub.newChannel(channelId);
> 
> const mock =  (data) => {
>     return new Promise((resolve) => {
>         setTimeout((e)=> {
>             resolve('timeout');
>         }, 2000)
>     })
> }
> 
> channel.listen("test", mock);
> 
> const dictionaryResult = channel.send('test', {a:123})
> dictionaryResult[channelId].then(r => {
>     console.log(r) //expect 'timeout'
> })
> ```
> 
> You can also use a generator in `channel.runGenerator` and use `delay` instead of the timeout.

great! Thank u!
